on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.1.1, latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install packages
        run: sudo apt-get -qy install cmake
      - name: Install libgraphqlparser
        run: |
          wget https://github.com/graphql/libgraphqlparser/archive/v0.7.0.tar.gz
          tar -xzvf v0.7.0.tar.gz
          cd libgraphqlparser-0.7.0/ && sudo cmake . && sudo make && sudo make install
      - name: Install shards
        run: shards install
      - name: Run tests
        run: crystal spec --order=random --error-on-warnings
        env:
          LD_LIBRARY_PATH: /usr/local/lib